# Generated by Django 3.2.6 on 2021-11-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quilitienda', '0003_auto_20211105_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
