# Generated by Django 3.2.6 on 2021-11-25 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quilitienda', '0007_departamento_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quilitienda.departamento'),
        ),
    ]
