# Generated by Django 3.2.6 on 2021-12-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quilitienda', '0010_auto_20211201_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='apellido',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
